# Название workflow, описывает его цель
name: Generate Changelog  

on:
  push:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2  
        with:
          fetch-depth: 0  

      - name: Download and Install git-cliff
        run: |  
          curl -L "https://github.com/orhun/git-cliff/releases/download/v2.2.1/git-cliff-2.2.1-x86_64-unknown-linux-gnu.tar.gz" -o git-cliff.tar.gz  
          tar -xzf git-cliff.tar.gz  
          mv git-cliff-2.2.1/git-cliff /usr/local/bin/  

      - name: Generate Changelog
        run: git-cliff --config cliff.toml --output CHANGELOG.md

      - name: Create version directory
        run: |
      
          mkdir -p ./docs/
          cp ./CHANGELOG.md ./docs/
  
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          GITHUB_TOKEN: ${{ secrets.REP_TOKEN }}
          publish_dir: ./docs/
          keep_files: true
